services:
  hardhat:
    build:
      context: contracts
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: ["npx", "hardhat", "compile"] 
    volumes:
      - ./shared/artifacts:/app/artifacts
      - ./shared/typechain-types:/app/typechain-types
  test:
    build:
      context: contracts
      dockerfile: Dockerfile
    command: ["npx", "hardhat", "test"]
    volumes:
      - ./shared/artifacts:/app/artifacts
      - ./shared/typechain-types:/app/typechain-types

  run:
    build:
      context: contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    command: ["npx", "hardhat", "node"]
    networks:
      - blockchain-network
    volumes:
      - ./shared/artifacts:/app/artifacts
      - ./shared/typechain-types:/app/typechain-types

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - run
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=your_jwt_secret_key
      - BLOCKCHAIN_URL=http://run:8545
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - CHICKEN_EGG_TRACKER_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - FARM_ADDRESS=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
      - AUTHORITY_CENTER_ADDRESS=0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
    networks:
      - blockchain-network
    volumes:
      - ./shared/artifacts:/app/src/contract-artifacts
      - ./shared/typechain-types:/app/src/contract-typechain

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
      - run
    volumes:
      - ./shared/artifacts:/app/artifacts
      - ./shared/typechain-types:/app/typechain-types
      - ./shared:/app/shared
    networks:
      - blockchain-network

  deploy:
    build:
      context: contracts
      dockerfile: Dockerfile
    command: ["npx", "hardhat", "run", "scripts/deploy.ts", "--network", "localhost"]
    depends_on:
      - run
    volumes:
      - ./shared/artifacts:/app/artifacts
      - ./shared/typechain-types:/app/typechain-types
      - ./shared:/app/shared
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge
