services:
  hardhat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8545:8545" # Map the Hardhat node port to the host
    stdin_open: true
    tty: true
    command: ["bash"] # Default command to keep the container interactive

  compile:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npx", "hardhat", "compile"]

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test:/app/test
    command: ["npx", "hardhat", "test"]

  run:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    command: ["npx", "hardhat", "node"]